### ISSUE TITLE
Lack of realtime protection + UI revamp

### ISSUE THREAD

**Issue by Murkdum** [flathub/com.gitlab.davem.ClamTk#11]
I was wondering if I could do some updates to clamtk in terms of real time scans (scan a recently changed file or directory), allowing the usage of the systray to allow those background checks and monitoring while also revamping the UI. 
Since I'm at it, integrating GUFW bits of code into clamtk to centralize firewall + AV on the same gui. 

I've already forked the project, but would want to know if I could proceed with said changes, to later on merge via PR,

Best regards

**Comment by refi64** [comment]
If you fork the project to change the scope that much, I'd definitely recommend just using a new name for it with a separate Flatpak.
